### ISSUE TITLE
pySMART lacks Python 3.8 compatibility

### ISSUE THREAD

**Issue by MichaIng** [HTPC-Manager/HTPC-Manager#3]
When having `pySMART` installed from PyPI (via `pip`), server start fails with the following error message:
```
Aug 25 19:38:01 VM-Bullseye python3[3322]: Traceback (most recent call last):
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/mnt/dietpi_userdata/htpc-manager/Htpc.py", line 269, in <module>
Aug 25 19:38:01 VM-Bullseye python3[3322]:     main()
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/mnt/dietpi_userdata/htpc-manager/Htpc.py", line 266, in main
Aug 25 19:38:01 VM-Bullseye python3[3322]:     start()
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/mnt/dietpi_userdata/htpc-manager/htpc/server.py", line 191, in start
Aug 25 19:38:01 VM-Bullseye python3[3322]:     logger.info("Starting up webserver")
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/usr/lib/python3.8/logging/__init__.py", line 1434, in info
Aug 25 19:38:01 VM-Bullseye python3[3322]:     self._log(INFO, msg, args, **kwargs)
Aug 25 19:38:01 VM-Bullseye python3[3322]:   File "/usr/lib/python3.8/logging/__init__.py", line 1565, in _log
Aug 25 19:38:01 VM-Bullseye python3[3322]:     fn, lno, func, sinfo = self.findCaller(stack_info, stacklevel)
Aug 25 19:38:01 VM-Bullseye python3[3322]: TypeError: findCaller() takes from 1 to 2 positional arguments but 3 were given
```
The reason is that `pySMART` overrides the `findCaller` function in a way that is not Python 3.8 compatible. There is an upstream fix available: https://github.com/freenas/py-SMART/commit/c5d6aabc80854ef27d9a7e4c4b2828478db5bf9d
But it has not yet been uploaded to the PyPI repository: https://pypi.org/project/pySMART/

**Comment by gmiranda** [comment]
Hi @MichaIng 

How about including the fixed pySMART in the modules dir? I'm running it that way

**Comment by MichaIng** [comment]
Good idea, at least until a new release is uploaded to PyPI. Probably `libs` directory fits better, but didn't test in which case it is correctly loaded?

**Comment by cooperdk** [comment]
That's not enough, you will get a cherrypy error right after. 

  File "/storage/.local/lib/python3.8/site-packages/cherrypy/_cpconfig.py", line 270, in _engine_namespace_handler
    plugin = getattr(engine, plugin)
AttributeError: 'Bus' object has no attribute 'timeout_monitor'

Called by htpc.server line 195

**Comment by MichaIng** [comment]
Is there an alternative to pySMART? Looking at the project, the original was abandoned and I don't see someone that seems responsible for doing the PyPI uploads at least.

However, for now adding the fixed version statically sounds like a solution. How would one do it, simply adding https://github.com/freenas/py-SMART/tree/master/pySMART to our modules or libs directory? (I have really minimal experience with Python projects 😅!)
And does it actually make a difference if we add it to modules or libs? The latter just feels more correct here since it contains (mostly contained, before your cleanup) external Python modules/libs while the modules dir contains our internal plugins. Makes sense to me to keep this separated, but again, based on very limited Python project knowledge.

**Comment by gmiranda** [comment]
@MichaIng pySMART has been copied/ported from FreeNAS to pypi, but it's already older than the github release. And it doesn't work since it does not contain the required fix that you pointed out.

There's also this other project but it's not actively maintained (or so it seems): https://pypi.org/project/pySMART.smartx/

**Comment by MichaIng** [comment]
pySMART.smartx last release is older than official pySMART version at PyPI and also the Git repo does not show any activity since last release: https://github.com/smartxworks/pySMART
So yes, that doesn't seem to be an option.

>  And it doesn't work since it does not contain the required fix that you pointed out.

You mean the version at PyPI? That is still true sadly. The FreeNAS GitHub repo however has the fix, I'm just not sure whether it works to simply put fork it into our modules or libs directory. libs seems to fit better IMO as it contains and contained other 3rd party libraries before and "modules" looks more like HTPC-Manager software modules, hence internal ones.

I should simply try it out and learn a bit about how Python works by this 😅. Becomes more urgent for my major project as of Debian Bullseye release this summer with Python 3.9.

**Comment by gmiranda** [comment]
I was exactly trying to implement that: submodules. There are some limitations: you can't just import part of the project tree. You can however use symlinks and that's what #22 does.

Please have a look at it.

I've also noticed another bug/feature request: when running HTPCManager as a normal user with SMART enabled and a sudoers entry for smartctl, our stats.py complains that we're not running as an admin. That check is redundant in the sudoers case. Perhaps this should go into another issue.

**Comment by MichaIng** [comment]
An upload of the new pySMART version is planned for today, which solves the issue. The only question is whether we want to explicitly state a minimum version string in our [requirements.txt](https://github.com/HTPC-Manager/HTPC-Manager/blob/master2/requirements.txt)?
