### ISSUE TITLE
CherryPy version

### ISSUE THREAD

**Issue by MichaIng** [HTPC-Manager/HTPC-Manager#30]
Currently we set the CherryPy<9.0 via [requirements.txt](https://github.com/HTPC-Manager/HTPC-Manager/blob/master2/requirements.txt) but I'm actually not keen to keep it on an over 4 years old version forever.

@gmiranda 
You mentioned that it performs better, and I see the HTTP engine indeed changed with v9.0: https://github.com/cherrypy/cherrypy/blob/main/CHANGES.rst#v900
However, I tested the newest v18.6.1 (after removing the obsolete and conflicting config to disable timeout monitoring) and it works very well here, no performance drop recognisable. Can you check if you if it's still slower and how I can replicate?

**Comment by MichaIng** [comment]
One PR which enables support for any higher CherryPy version without changing something on <9.0: #31

**Comment by MichaIng** [comment]
On the newest CherryPy version, also the error about (by client) untrusted self-signed TLS certificate is gone (hidden): https://github.com/HTPC-Manager/HTPC-Manager/pull/28#issuecomment-879246793
It doesn't solve the underlying issue that clients don't trust it, regardless whether imported on OS-level, but at least the logs are not spammed 🙂.

**Comment by MichaIng** [comment]
I just learned that the documented engine change is just a structural one, not functional one: Code has been shifted into the dedicated cheroot project but not changed. Of course it developed further afterwards.

**Comment by MichaIng** [comment]
Found it. The idle CPU usage is significantly higher. On my VM with CherryPy < 9 it its mostly 0% with a short peak to 1% (average over a second) every ~5 seconds. With CherryPy == 9.0.0 and above, it is never below 1% (average over a second), mostly jumps between 1% and 2%, sometimes 3%. That is multiple times more, on a small SBC likely a real problem.

I further narrowed it down to the cheroot version 8.4.2 (Jul 28, 2020) which introduced this significant idle CPU usage increase. On v8.4.1 this is much lower, but still significantly than with CherryPy 8.x (where cheroot is not used). The earlier idle CPU change occurred from cheroot 8.0.0 to 8.1.0.

Latest CherryPy with cheroot 8.0.0 has nearly identical CPU usage than CherryPy v8.9.1 (with engine included). The centisecond (?) counter in htop raises reliably by 1 every 5 seconds with CherryPy v8.9.1 and reliably every 4 seconds with latest CherryPy + cheroot v8.0.0 (which works even that this CherryPy version declares cheroot>=8.2.1 as requirement).

cheroot v8.1.0 implemented this change which implements a new connection manager to handle idle connections and keep alive requests better. But this seems to imply significantly higher CPU load: https://github.com/cherrypy/cheroot/pull/199

Interestingly v8.4.2 implemented a performance regression "fix" that was implemented exactly with the above PR: https://github.com/cherrypy/cheroot/pull/308
It reduces the connection timeout (?) from 0.1 to 0.01 and I can only assume that some loop it processed hence 10 times more often, leading to the significantly raised idle frequency. It however seems to increase request performance, as the 0.1 delay adds up on request answers, which is now reduced to 0.01s.

Those PRs seem to fix real problems, so we do a trade-off by using the old CherryPy here, regarding concurrent connections and keep alive requests. I'll report/forward those findings to the CherryPy/cheroot team, probably something can be done to reduce overhead on those loops. Also the changelog mentions that "a better fix is yet to come", which I cannot find yet. Probably a push can help 🙂.
__________
**EDIT: Ah https://github.com/cherrypy/cheroot/pull/311 seems to address the timeout-related performance issues in a better way, but the timeout is left at 0.01. I'll now try to increase this timeout on newer cheroot versions, to see the impact on idle CPU usage.
EDIT2: Bingo! Adjusting the timeout [here](https://github.com/cherrypy/cheroot/blob/e2cfa19/cheroot/connections.py#L210) restores minimal idle CPU usage 🥳.**

**Comment by MichaIng** [comment]
Reported: https://github.com/cherrypy/cheroot/issues/378

**Comment by gmiranda** [comment]
> 
> 
> Found it. The idle CPU usage is significantly higher. On my VM with CherryPy < 9 it its mostly 0% with a short peak to 1% (average over a second) every ~5 seconds. With CherryPy == 9.0.0 and above, it is never below 1% (average over a second), mostly jumps between 1% and 2%, sometimes 3%. That is multiple times more, on a small SBC likely a real problem.
**

That's exactly the issue I ran into. I recall making some changes to support and optimize 9.0 and above, but it was still worse. Glad that you've gone further!

**Comment by MichaIng** [comment]
Jep, and there is already a PR open for a long time which fixes the issue. I probably found other ways to further enhance the connection manager, so probably we can make it faster and consume less CPU time on idle then before.

**Comment by MichaIng** [comment]
Finally we should have solved it via: https://github.com/cherrypy/cheroot/pull/401
`cheroot` v8.6.0 has just been released with this change: https://pypi.org/project/cheroot/#history
